### ISSUE TITLE
One-Time Password

### ISSUE THREAD

**Issue by AlexandreCassagne** [ahmedsakr/wstrade-api#20]
Does this wrapper support one-time passwords?

**Comment by ahmedsakr** [comment]
At this time, i don’t believe so. I think 2FA is in the dev’s team pipeline, too. Logging in right now seems to be constrained to email and password only.

**Comment by AlexandreCassagne** [comment]
@ahmedsakr After some research on my end, I figured out that the only difference with the current authentication scheme, is that :

1. Make the Login request as is (email/password) 
2. If authentication failed because you need a one-time password, the user receives the OTP by SMS
3. At this point, make the same Login request again, with a ‘otp’ field in the JSON in addition to the usual email and password. 

I hope this helps in implanting the specs !

**Comment by ahmedsakr** [comment]
@AlexandreCassagne Thanks for the detailed response. Just to clear up some confusion on my side, are you saying that the WealthSimple Trade app currently supports one-time passwords? I was looking into the security menu in the app, and I only see biometrics (face id, touch id), passcode (4-digit numeric code), and 'None' (log in with email and password only)

**Comment by AlexandreCassagne** [comment]
Good point. It seems you can only enable it in Wealthsimple (the regular app)

![AFFFE5D6-ECD3-4174-9330-8128BF1AD688](https://user-images.githubusercontent.com/541043/82506304-6adc0a00-9acd-11ea-89c0-93d5545937da.png)

Once enabled, I can confirm the Wealthsimple Trade endpoints require the one-time password.

**Comment by ahmedsakr** [comment]
Amazing, thank you for the feedback, @AlexandreCassagne. I will flag this issue as investigate so it can be further looked into and come up with a suitable solution for the wrapper. My quick impression is that this change might require a behavioural change for the `'login` API, so this might be a good addition for `v1.0.0` of wstrade-api.

**Comment by AlexandreCassagne** [comment]
Sounds good, for the record I'm personally working on a Go version of the API which I will publish at some point. Feel free to message me if you have anything I can help with

**Comment by austingreisman** [comment]
> At this time, I don’t believe so. I think 2FA is in the dev’s team pipeline, too. Logging in right now seems to be constrained to email and password only.

2FA works if you enter in the email, password, and "ota" after receiving the code.

Example in Python:
`request = requests.post('https://trade-service.wealthsimple.com/auth/login', data={'email':'austin@gmail.com', 'password':'Passw0rd'})`

Then, after code is received "SMS for me".

`sms_code_response = requests.post('https://trade-service.wealthsimple.com/auth/login', data={'email':'austin@gmail.com', 'password':'Passw0rd','otp':'107438'})`

Then you'll get the access tocken in the header of `sms_code_response`

Method was mentioned in https://github.com/MarkGalloway/wealthsimple-trade/issues/4#issuecomment-616218419

**Comment by dillonco** [comment]
Just started having problems logging in and I started getting OTP emails. I never turned it on, so I wonder if they automatically turned it on for everyone?

**Comment by ggmichaelgo** [comment]
I had to write a quick and dirty ruby script to check my Gmail inbox, and generate the tokens .... :|

[Tutorial to get gmail inbox with Ruby](https://developers.google.com/gmail/api/quickstart/ruby)

**Comment by ahmedsakr** [comment]
@dillonco Yep, I just started getting the same thing. Well, this issue just got a lot higher priority

**Comment by ahmedsakr** [comment]
@dillonco I am adding a third parameter to `login()` called `otp_func` that is an async function to retrieve the code.

```
wealthsimple.login('test@example.ca', 'password', async () => '153593')
```

This should be backwards compatible and should be customizable to provide a script as the async function to get the OTP code. Or you can simple just add the number yourself when you get it.

How do you feel about this temp solution until a proper method is developed for `v1.0.0`?

**Comment by dillonco** [comment]
Yeah sounds good and should work for me

**Comment by ahmedsakr** [comment]
Okay, i merged the fix and it's in `v0.11.0`. I will re-open this issue, however, as there will still be an API change with this for `v1.0.0`.

**Comment by ahmedsakr** [comment]
https://github.com/ahmedsakr/wstrade-api/blob/1.0.0-develop/src/auth.js

I have modified the one-time password API for `v1.0.0`. The `auth` module now expects an `otp` handler to be registered through `trade.auth.on('otp', () => { /*handler */ })`

So you would log in something like this:

```
trade.auth.on('otp', () => '134528');

trade.auth.login('hello@example.ca', 'mysweetpassword');
```

Comments or concerns are appreciated.

**Comment by ggmichaelgo** [comment]
I really like this pattern @ahmedsakr !!! Thank you for your great work! Hopefully, I can contribute to this project soon :)

**Comment by ahmedsakr** [comment]
I am happy you like it, and thanks! It's my pleasure. Looking forward to you contributing. :)
