### ISSUE TITLE
API usage

### ISSUE THREAD

**Issue by artem055** [ahmedsakr/wstrade-api#32]
tried to use first .login function with no luck
I'm new to node.js and of course may doing something wrong way 
however.  lack of documentation (with working examples) is an issue 
In short, I followed installation instructions: 

what  i did 
downloaded and installed node.js ( for Windows)  

1) created empty folder for project (test) 
run npm init to get package.json file 
2) run npm install git+ https://github.com/ahmedsakr/wstrade-api.git
so i got modules/library downloaded  and my   package.json has been updated
3)  created simple file test.mjs  (have to use .mjs extension, otherwise , IMPORT will not work) with code

import trade from 'wstrade-api';
trade.login('email', 'password')
    .then(data => console.log(data)); 

when debug in visual studio code or when i just run node test.mjs   i'm getting error :  trade.login is not a function

pasted error below : 
-------------------------------------------------
C:\Program Files\nodejs\node.exe .\..\test\test.mjs
Debugger listening on ws://127.0.0.1:50518/fa573159-39a9-4b27-ab9c-b04d74562c20
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
(node:4524) ExperimentalWarning: The ESM module loader is experimental.
(node:4524) ExperimentalWarning: The ESM module loader is experimental.
Waiting for the debugger to disconnect...
file:///k:/node.js/test/test.mjs:2
trade.login('sdfdsf','dsfgdg')
      ^

TypeError: trade.login is not a function
    at file:///k:/node.js/test/test.mjs:2:7
    at ModuleJob.run (internal/modules/esm/module_job.js:139:37)
    at async Loader.import (internal/modules/esm/loader.js:179:24)
Process exited with code 1

----------------------------------

the folder structure i have is 
test->
 test.mjs  
package.jason
package-lock.jason
node_modules -> 
http-status
node-fetch
wstratde-api

package.json 

{
  "name": "test",
  "version": "1.0.0",
  "description": "test",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "type": "module",
  
  "dependencies": {
    "wstrade-api": "git+https://github.com/ahmedsakr/wstrade-api.git"
  }
}

node.js version is 12.8.1 

screenshots of my visual studio environment : 

![pic1 ](https://user-images.githubusercontent.com/70645213/92494240-7742ba80-f1c3-11ea-8c69-6c546eb6c048.jpg)
![pic2](https://user-images.githubusercontent.com/70645213/92494242-77db5100-f1c3-11ea-9627-f37b2037ddb7.jpg)

**Comment by ahmedsakr** [comment]
https://github.com/nodejs/help/issues/2874#issuecomment-667095206

Maybe this will help

**Comment by silvavn** [comment]
Also came across this and the ES importer error. Is it possible to provide a cookbook, quickstart or minimal working version?

**Comment by ahmedsakr** [comment]
There is an existing issue for adding detailed examples in the API: https://github.com/ahmedsakr/wstrade-api/issues/10

I haven't gotten around to it as I have been busy with work then and now I'm back in university for my last year. However, I will prioritize it since it's time that it is done. Hopefully I will have extensive examples for all APIs within a few weeks.

**Comment by mdy405** [comment]
i got the s same issue 
`
const trade = require('wstrade-api')
const wsLogin = async (userName, password) => {
    await trade.default.login(userName, password)
        .then(data => console.log(data))
        .catch(err => console.log(err))
}

wsLogin('me@gmail.com','*********')
`

**Comment by ahmedsakr** [comment]
@artem055 you are using `.mjs`, so you will have to use `trade.default` to get the functions
@mdy405 you will have to change your first line to `const trade = require('wstrade-api').default`.

I need to look into `.mjs` and how node treats ES6 module files.

**Comment by mdy405** [comment]
@ahmedsakr thanks for quick reply its work for me !

**Comment by ahmedsakr** [comment]
I have now optimized `wstrade-api` for non-ES6 importing and requiring. It has been merged to `1.0.0-develop` and will be available when I release `1.0.0`. This means you will be able to do this in non-ES6:

`const trade = require('wstrade-api');`

You won't need the `.default` at the end.

`*.mjs` files won't require a `.default` intermediary anymore either.
