### ISSUE TITLE
Trades in excess of 7 per hour

### ISSUE THREAD

**Issue by vxsl** [ahmedsakr/wstrade-api#39]
Regarding the following excerpt of the README:

> A user of wstrade-api has observed that trades in excess of 7 per hour are rejected by the WealthSimple Trade servers. You can use this observation as a baseline of how many trades you can perform on an hourly basis.

Is it possible that this is due to the expiration of an access token? See the [Wealthsimple API](https://developers.wealthsimple.com/#section/Authentication/Refreshing-an-Access-Token). For the record, I have not used wstrade-api to make any trades yet, so I can't comment on the 7-per-hour restriction personally.

Edit: there is also the [rate limit](https://developers.wealthsimple.com/#operation/RateLimit). Not sure if these are useful observations.

Edit again: Oops, I just realized this documentation is for WS, not WS Trade 😖 I'll keep this up in case it is somehow useful

**Comment by ahmedsakr** [comment]
I don't believe it has to do with the token expiring. The order goes through but its status appears as rejected. So the request is a `201`, but the WealthSimple Trade market backend rejects the order.

Here is a picture of rejected status trade.

![rejected-status](https://user-images.githubusercontent.com/7413778/95691285-050f2c80-0bec-11eb-90a4-8470c441e396.png)
