### ISSUE TITLE
trade.login() -> 403 Forbidden

### ISSUE THREAD

**Issue by vxsl** [ahmedsakr/wstrade-api#41]
I am for the first time receiving a 403 response when calling `trade.login()` with the correct username and password:

`{url: 'https://trade-service.wealthsimple.com/auth/login', status: 403, statusText: 'Forbidden', headers: Headers, counter: 0}`

Anybody else experiencing this today?

**Comment by ahmedsakr** [comment]
Nope, I just logged in with the API and it worked.

Are you able to login normally through the application?

**Comment by vxsl** [comment]
Cool, glad to hear that. Yes, it's definitely the right set of credentials, and I've tried it from multiple origins with the same response, so it must be something with my account. This can be closed

**Comment by vxsl** [comment]
Hm, ok, actually, I was wrong that it had the same response on multiple origins. It only fails when I call the function from my VPS. Have you had any experience with WS blocking IPs in the past?

**Comment by ahmedsakr** [comment]
I haven't experienced IPs being blocked. Who do you rent your VPS from?

**Comment by vxsl** [comment]
A company called [Hostinger](https://www.hostinger.com/vps-hosting#). Noticed that pings to trade-service.wealthsimple.com go through. Odd.
