### ISSUE TITLE
Persistent storage of tokens

### ISSUE THREAD

**Issue by ahmedsakr** [ahmedsakr/wstrade-api#45]
Access tokens are good for a while. wstrade-api currently doesn't have any way of storing tokens, but you can store them yourself if you wanted. Would it be beneficial to have a built-in solution for storage of tokens? the solution would also maintain the expiry date of the token and invalidate it then.

**Comment by GabrielBottari** [comment]
How would you figure out the expiration time of both the access and refresh tokens?

**Comment by ahmedsakr** [comment]
The access token is good for 2 hours and the refresh token is good for longer although not known. WS Trade actually returns a new refresh token when you invoke auth.`refresh`, so I don't think it'll be necessary to know the expiry time of the refresh token.

**Comment by ahmedsakr** [comment]
Also, since i created this issue in early November, I've had a change in opinion. I think creating a persistent storage solution in wstrade-api might be overreaching into the user's business logic.

A better solution might be to provide an auth event to hook onto with auth.`on` (event name like `loginsuccess`) which will give t the function the email and tokens in which they can store it the way they like.


```javascript
auth.on('loginsuccess', async (email, tokens) => {
   // user implements logic to store in database, for example
}
```

**Comment by GabrielBottari** [comment]
How is that different from a normal asynchronous call? Instead it's a callback? Or does it do additional work in the background, like refreshing tokens for you?

**Comment by ahmedsakr** [comment]
the idea behind the `loginsuccess` event (at least how I think of it) would be to allow wstrade-api users to separate the logic of storing tokens from logging in. Currently, you would have to write something like this.


## login.js
```javascript

import { auth } from 'wstrade-api'

//
// assume one-time password stuff is already setup with auth.on('otp', ...)
//

async saveUser() {
  await psql.query("....");
}}

(async () => {

  // Attempt a login
  await auth.login('example@example.ca', 'mypass');

  // Now that we succeeded, the tokens have been saved to auth.tokens
  // Lets save the tokens in the database
  await saveUser();
})();
```

Not too bad, but it introduces code coupling in the file, and also having to sequentially query the database in the code.

If a `loginsuccess` event was added to the auth.`on` API, the user could have a separate module for handling storing of the token, so their code can look something like this.

## login.js
```javascript
import { auth } from 'wstrade-api'

//
// assume one-time password stuff is already setup with auth.on('otp', ...)
//

(async () => {

  // Attempt a login
  await auth.login('example@example.ca', 'mypass');
})();
```

## persist.js

```javascript

import { auth } from 'wstrade-api';

auth.on('loginsuccess', async (email, tokens) => {
  await psql.query("....");
});


```

Functionally, both these patterns do the same thing. It would just be support for distributing the logic.
