### ISSUE TITLE
Market Buys/Sells

### ISSUE THREAD

**Issue by ahmedsakr** [ahmedsakr/wstrade-api#8]
Market buys and sells are currently not supported by the wrapper. I was not able to figure out the appropriate parameters to make a successful market buy / sell API, but my hunch is that it has to do with the current price of the stock.

**Comment by vlad-pisanov** [comment]
For some strange reason, my market buy orders never get filled. They show up in the app as "pending" but that's it. 😞 If I place a market buy order in the app, it gets filled right away. Have you had any luck with market orders actually being filled through the API?
