### ISSUE TITLE
Auth route returning 401: Not authorized with correct login information

### ISSUE THREAD

**Issue by landoncolburn** [ahmedsakr/wstrade-api#81]
Might be a backend change? Anyone else having similar issues?

**Comment by landoncolburn** [comment]
Took a peak behind the web app - the official app is making requests to https://api.production.wealthsimple.com/v1/oauth/token where the API is making requests to https://trade-service.wealthsimple.com/auth/login

**Comment by landoncolburn** [comment]
I got a successful response from the server by hitting the api.production subdomain with the following fields:
`"grant_type": "password",
    "username": "<email>",
    "password": "<password>",
    "skip_provision":true,
    "otp_claim":null,
    "scope":"invest.read invest.write mfda.read mfda.write mercer.read mercer.write trade.read trade.write empower.read empower.write tax.read tax.write",
    "client_id":"<64 char hex code found from web app>"`

**Comment by ahmedsakr** [comment]
i just tried out the latest (`v1.3.0`) and it worked fine for me. Are you setting up the OTP as instructed in the docs?

**Comment by landoncolburn** [comment]
This is the same body used by the web app - I also had to include the following headers:
`"x-wealthsimple-otp": "<otp>, "X-Wealthsimple-Client": "Wealthsimple.js", "X-WS-Device-ID":"<32 char hex>"`

**Comment by landoncolburn** [comment]
> i just tried out the latest (`v1.3.0`) and it worked fine for me. Are you setting up the OTP as instructed in the docs?

Yeah I did - I even verified it both in Postman and on their web app.

**Comment by ahmedsakr** [comment]
Can you share how you are setting it up? as mentioned, I just tested out `v1.3.0` and I was able to login as usual and I got my oauth2 tokens and accessed other APIs. So I don't believe at this point that there is a regression in the API.

**Comment by landoncolburn** [comment]
Sure! This is all I have setup so far:
`require('dotenv').config();
const twofactor = require("node-2fa");
const { auth } = require('wstrade-api');

const getToken = (secret) => twofactor.generateToken(secret);

auth.on('otp', getToken(process.env.TFA_SECRET));

(async () => {
	await auth.login(process.env.EMAIL, process.env.PASSWORD);
})().catch(error => console.log(error))`

**Comment by ahmedsakr** [comment]
have you tested if your OTP func `getToken` is returning the correct value? with like a simple `console.log` to make sure that when `wstrade-api` calls it, it's giving it the correct code

**Comment by ahmedsakr** [comment]
i see from `node-2fa`'s docs, that it returns an object with a `.token` property. You will have to manually extract that property value in your function like this:


```javascript
const getToken = (secret) => twofactor.generateToken(secret).token;
```

**Comment by landoncolburn** [comment]
Wow. I cannot believe it was that simple. Thank you and sorry for your time

**Comment by ahmedsakr** [comment]
No problem. I just took a look at the `auth` docs I made and they aren't clear on this. Thanks for bringing it up, I'll update the docs on the next push.
