### ISSUE TITLE
Invalid JSON returned when logging in.

### ISSUE THREAD

**Issue by dhrabarchuk75** [ahmedsakr/wstrade-api#97]
Here is the error message I get with trying to log in:

login promise rejected
{ FetchError: invalid json response body at https://trade-service.wealthsimple.com/auth/login reason: Unexpected token < in JSON at position 0 <!DOCTYPE html>
....
<h1>Access denied</h1>\n  <p>This website is using a security service to protect itself from online attacks.</p>\n  <ul class="cferror_details">\n    <li>Ray ID: 62edcb83ca467f94</li>\n    <li>Timestamp: 2021-03-12 14:43:27 UTC</li>\n    <li>Your IP address: 65.92.53.231</li>\n    <li class="XXX_no_wrap_overflow_hidden">Requested URL: trade-service.wealthsimple.com/auth/login </li>\n    <li>Error reference number: 1020</li>\n    <li>Server ID: FL_14F299</li>\n    <li>User-Agent: node-fetch/1.0 (+https://github.com/bitinn/node-fetch)</li>\n  </ul>\n</div>\n\n  </div>\n</body>\n</html>'

**Comment by dhrabarchuk75** [comment]
I have do nothing other than read in account activity and balances, reading only.

**Comment by ahmedsakr** [comment]
Issue already raised: https://github.com/ahmedsakr/wstrade-api/issues/96

**Comment by dhrabarchuk75** [comment]
Let me know if I can help, I use CF all day long  . . .

**Comment by ahmedsakr** [comment]
Your expertise will actually be very needed. Do you discord?

**Comment by dhrabarchuk75** [comment]
not yet, but I'm downloading it now

**Comment by ahmedsakr** [comment]
Okay, if you'd like then we could just create a thread in the discussions section here instead, so you don't have to sign up to another service

**Comment by ahmedsakr** [comment]
https://github.com/ahmedsakr/wstrade-api/discussions/98

**Comment by dhrabarchuk75** [comment]
I registered with dhrabarchuk

**Comment by ahmedsakr** [comment]
there is a four-digit tag also associated with your username. Can you also give me that?

**Comment by dhrabarchuk75** [comment]
dhrabarchuk#6105
